name: brew test-bot
on:
  push:
    branches: main
  pull_request: []
jobs:
  test-bot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax

      - name: Run brew test-bot --only-formulae
        if: github.event_name == 'pull_request'
        run: brew test-bot --only-formulae
