name: brew test-bot
on:
  push:
    branches: main
  pull_request: []
jobs:
  test-bot:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - name: Update Homebrew
        run: brew update

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Homebrew
        run: |
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/WootingKb/homebrew-wooting"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax

      - name: Run brew test-bot --only-formulae
        if: github.event_name == 'pull_request'
        run: brew test-bot --only-formulae
